data:
  dir: 'data/SIAR'
  
train:
  debug: True
  pre_train: True
  batch_size: 2
  max_epochs: 3
  log_every_n_steps: 1
  device: 'cpu'
  weight_decay: 0.01
  strategy: 'auto' #'ddp_find_unused_parameters_true'
  accumulate_grad_batches: 1


model:
  checkpoint: False # 'checkpoints/lightning_logs/version_0/checkpoints/epoch=2-step=15.ckpt'
  upsampler_gt: 'unet' # upsampler for ground truth
  upsampler_sl: None #'unet' # upsampler for shadow and light
  upsampler_ob: None #'unet' # upsampler for objects (masks + rgb)
  swin:
    checkpoint: '' #'swin_checkpoints/None/swin_encoder_epoch_1.pt'
    use_checkpoint: False
    patch_size: [2, 4, 4]    
  unet_gt:
    decoder:
      output_dim: 3
      f_maps: [96, 192, 384, 768]
      basic_module: 'DoubleConv'
      conv_kernel_size: 3
      conv_padding: 1
      layer_order: 'gcr'
      num_groups: 8
      is3d: True
      layers_no_skip:
        size: [[96, 48, 5, 128, 128], [48, 24, 10, 256, 256]]
        scale_factor: 2 
      omit_skip_connections: True
  unet_sl:
    decoder:
      output_dim: 2
      f_maps: [96, 192, 384, 768]
      basic_module: 'DoubleConv'
      conv_kernel_size: 3
      conv_padding: 1
      layer_order: 'gcr'
      num_groups: 8
      is3d: True
      layers_no_skip:
        size: [[96, 48, 5, 128, 128], [48, 24, 10, 256, 256]]
        scale_factor: 2
      omit_skip_connections: True
  unet_ob:
    decoder:
      output_dim: 4
      f_maps: [96, 192, 384, 768]
      basic_module: 'DoubleConv'
      conv_kernel_size: 3
      conv_padding: 1
      layer_order: 'gcr'
      num_groups: 8
      is3d: True
      layers_no_skip:
        size: [[96, 48, 5, 128, 128], [48, 24, 10, 256, 256]]
        scale_factor: 2
      omit_skip_connections: True