data:
  # Name of dataset: 'SIAR', 'SIAR_SL', 'SIAR_OCC', 'SIAR_OCC_Binary', 'SIAR_OCC_AND_SL', 'SIAR_EVAL'
  dataset: 'SIAR'
  # Split version to use
  split_dir: 'split-1_80_10_10'
  # Number of workers for dataloader
  num_workers: 1
  # Path to dataset directory that includes SIAR data (path/SIAR), generated occlusion masks (path/SIAR_OCC). If False, expects data to be in data directory of project
  path_to_data: False
  # Path where to save evaluation output (Only used for evaluation script)
  eval_output: evaluation_output
    
train:
  debug: True
  pre_train: False
  batch_size: 2
  lr: 1e-3
  max_epochs: 100
  log_every_n_steps: 15
  log_img_every_n_epochs: 5
  device: 'gpu'
  # Select loss function: 'base_loss', 'reconstruction_loss', 'pre_train_loss', 'regularized_loss', 'stage_loss', 'light_and_shadow_loss', 'separate_head_loss'
  loss_func: 'separate_head_loss'
  stage: 'train_all'
  # Select metric to use for comparison: 'MSE', 'SSIM', 'MAE', 'BCE', 'BCEWithLogits', 'MAE_weighted'
  metric_all: 'MAE' # used for reconstruction_loss
  metric_gt: 'MAE'
  metric_sl: 'MAE'
  metric_ob: 'SSIM'
  # metric_occ_mask: 'BCE'  # 'MAE'
  metric_occ_mask: 'BCEWithLogits'
  metric_occ_rgb: 'MAE_weighted'  # 'MAE'
  lambda_binary_occ: False
  lambda_gt_loss: 1.0
  lambda_decomp_loss: 1.0
  lambda_occlusion_difference: 1e-3
  mask_decay: False # 1e-10
  weight_decay: False # 1e-5
  strategy: 'ddp_find_unused_parameters_true'
  accumulate_grad_batches: 4
  es_patience: 10


model:
  checkpoint: False
  upsampler_gt: 'unet' # upsampler for ground truth
  upsampler_sl: 'unet' # upsampler for shadow and light
  upsampler_ob: 'unet' # upsampler for objects (masks + rgb)
  swin:
    checkpoint: 'checkpoints/swin_checkpoints/swin_pretrain_from_ckpt/swin_encoder.pt'
    use_checkpoint: True
    frozen_stages: 4
    patch_size: [2, 4, 4]    
  unet_gt:
    freeze: False
    checkpoint: 'checkpoints/decoder_checkpoints/oi_pretrained/up_scale_gt_model.pt'
    decoder:
      output_dim: 3
      f_maps: [96, 192, 384, 768]
      basic_module: 'DoubleConv'
      conv_kernel_size: 3
      conv_padding: 1
      layer_order: 'gcr'
      num_groups: 8
      is3d: True
      layers_no_skip:
        size: [[96, 48, 5, 128, 128], [48, 24, 1, 256, 256]]
        scale_factor: 2 
      omit_skip_connections: False
  unet_sl:
    freeze: False
    checkpoint: 'checkpoints/decoder_checkpoints/sl_pretrained/up_scale_sl_model.pt'
    decoder:
      output_dim: 2
      f_maps: [96, 192, 384, 768]
      basic_module: 'DoubleConv'
      conv_kernel_size: 3
      conv_padding: 1
      layer_order: 'gcr'
      num_groups: 8
      is3d: True
      layers_no_skip:
        size: [[96, 48, 5, 128, 128], [48, 24, 10, 256, 256]]
        scale_factor: 2
      omit_skip_connections: False
  unet_ob:
    freeze: False
    checkpoint: 'checkpoints/decoder_checkpoints/occ_binary_pretrained/up_scale_ob_model.pt'
    decoder:
      output_dim: 4
      f_maps: [96, 192, 384, 768]
      basic_module: 'DoubleConv'
      conv_kernel_size: 3
      conv_padding: 1
      layer_order: 'gcr'
      num_groups: 8
      is3d: True
      layers_no_skip:
        size: [[96, 48, 5, 128, 128], [48, 24, 10, 256, 256]]
        scale_factor: 2 
      omit_skip_connections: False