data:
  # Name of dataset
  dataset: 'SIAR'
  # Split version to use
  split_dir: 'split-1_80_10_10'
  # (Optional) Manual path to dataset
  manual_dataset_path: '/home/fe/meinardus/decomposition_learning/data/SIAR_128'
  # Set validation set equal to train set to provoke overfitting and see if loss works
  sanity_check: False
  # Size of images
  img_size: 128 # 256 # 64
  
train:
  debug: True
  batch_size: 16
  max_epochs: 50
  eval_every: 2
  log_every: 15
  save_every: 10
  device: None
  lr: 3e-4

model:
  swin:
    checkpoint: 'swin_checkpoints/swin_pretrain_from_ckpt/swin_encoder.pt'
    use_checkpoint: True
    patch_size: [2, 4, 4]
    emb_dim: 768
  upsampler: None


