data:
  dir: 'data/SIAR'
  img_size: 64 # 256 # 64
  
train:
  debug: True
  batch_size: 1
  max_epochs: 300
  device: cpu
  lr: 3e-4

decomposer:
  swin:
    pretrained: ''
    use_checkpoint: False
    patch_size: [2, 4, 4]
    emb_dim: 768
  upsampler: None


