data:
  # Name of dataset
  dataset: 'SIAR_EVAL'
  # Split version to use
  split_dir: ''
  # Set validation set equal to train set to provoke overfitting and see if loss works
  sanity_check: False
  num_workers: 8
  preprocess: True
  eval_output: evaluation_output_no_pretrain
    
train:
  debug: False
  pre_train: False
  batch_size: 2
  lr: 1e-4
  max_epochs: 1000
  log_every_n_steps: 15
  device: 'cpu'
  # Select loss function: 'base_loss', 'reconstruction_loss', 'pre_train_loss', 'regularized_loss', 'stage_loss', 'light_and_shadow_loss', 'separate_head_loss'
  loss_func: 'separate_head_loss'
  # Select metric to use for comparison: 'MSE', 'SSIM', 'MAE'
  metric_gt: 'MAE'
  metric_sl: 'MAE'
  metric_ob: 'SSIM'
  metric_all: 'MAE'
  stage: 'train_all'
  weight_decay: 0.0
  mask_decay: 1e-4 # 1e-5
  lambda_binary_occ: 0.01
  lambda_gt_loss: 1.0
  lambda_decomp_loss: 1.0
  lambda_occlusion_difference: 1e-3
  strategy: 'ddp_find_unused_parameters_true'
  accumulate_grad_batches: 4
  es_patience: 10
  log_img_every_n_epochs: 5

model:
  checkpoint: 'checkpoints/final/swin_unet_unet_unet_from_checkpoint_all_epoch614.ckpt'
  upsampler_gt: 'unet' # upsampler for ground truth
  upsampler_sl: 'unet' # upsampler for shadow and light
  upsampler_ob: 'unet' # upsampler for objects (masks + rgb)
  swin:
    checkpoint: False
    use_checkpoint: False
    frozen_stages: 4
    patch_size: [2, 4, 4]    
  unet_gt:
    freeze: False
    checkpoint: False
    decoder:
      output_dim: 3
      f_maps: [96, 192, 384, 768]
      basic_module: 'DoubleConv'
      conv_kernel_size: 3
      conv_padding: 1
      layer_order: 'gcr'
      num_groups: 8
      is3d: True
      layers_no_skip:
        size: [[96, 48, 5, 128, 128], [48, 24, 1, 256, 256]]
        scale_factor: 2 
      omit_skip_connections: False
  unet_sl:
    freeze: False
    checkpoint: False
    decoder:
      output_dim: 2
      f_maps: [96, 192, 384, 768]
      basic_module: 'DoubleConv'
      conv_kernel_size: 3
      conv_padding: 1
      layer_order: 'gcr'
      num_groups: 8
      is3d: True
      layers_no_skip:
        size: [[96, 48, 5, 128, 128], [48, 24, 10, 256, 256]]
        scale_factor: 2
      omit_skip_connections: False
  unet_ob:
    freeze: False
    checkpoint: False
    decoder:
      output_dim: 4
      f_maps: [96, 192, 384, 768]
      basic_module: 'DoubleConv'
      conv_kernel_size: 3
      conv_padding: 1
      layer_order: 'gcr'
      num_groups: 8
      is3d: True
      layers_no_skip:
        size: [[96, 48, 5, 128, 128], [48, 24, 10, 256, 256]]
        scale_factor: 2 
      omit_skip_connections: False