data:
  # Name of dataset: 'SIAR', 'SIAR_SL', 'SIAR_OCC'
  dataset: 'SIAR_OCC'
  # Split version to use
  split_dir: 'split-1_80_10_10'
  # Set validation set equal to train set to provoke overfitting and see if loss works
  sanity_check: False
  num_workers: 16
    
train:
  debug: True
  pre_train: False
  batch_size: 16
  lr: 1e-3
  max_epochs: 500
  log_every_n_steps: 15
  device: 'cpu'
  # Select loss function: 'base_loss', 'reconstruction_loss', 'pre_train_loss', 'regularized_loss', 'stage_loss', 'light_and_shadow_loss', 'separate_head_loss'
  loss_func: 'separate_head_loss'
  # Select metric to use for comparison: 'MSE', 'SSIM', 'MAE'
  metric_gt: 'MAE'
  metric_sl: 'MAE'
  metric_ob: 'SSIM'
  metric_all: 'MAE'
  stage: 'train_gt'
  weight_decay: 0.01
  mask_decay: 1e-4 # 1e-5
  lambda_gt_loss: 1.0
  lambda_decomp_loss: 1.0
  lambda_occlusion_difference: 1e-3
  strategy: 'ddp_find_unused_parameters_true'
  accumulate_grad_batches: 4
  es_patience: 10


model:
  checkpoint: False
  upsampler_gt: 'unet' # upsampler for ground truth
  upsampler_sl: 'unet' # upsampler for shadow and light
  upsampler_ob: 'unet' # upsampler for objects (masks + rgb)
  swin:
    checkpoint: 'swin_checkpoints/swin_pretrain_from_ckpt/swin_encoder.pt'
    use_checkpoint: True
    frozen_stages: 4
    patch_size: [2, 4, 4]    
  unet_gt:
    freeze: True
    checkpoint: False
    decoder:
      output_dim: 3
      f_maps: [96, 192, 384, 768]
      basic_module: 'DoubleConv'
      conv_kernel_size: 3
      conv_padding: 1
      layer_order: 'gcr'
      num_groups: 8
      is3d: True
      layers_no_skip:
        size: [[96, 48, 5, 128, 128], [48, 24, 1, 256, 256]]
        scale_factor: 2 
      omit_skip_connections: False
  unet_sl:
    freeze: True
    checkpoint: False
    decoder:
      output_dim: 2
      f_maps: [96, 192, 384, 768]
      basic_module: 'DoubleConv'
      conv_kernel_size: 3
      conv_padding: 1
      layer_order: 'gcr'
      num_groups: 8
      is3d: True
      layers_no_skip:
        size: [[96, 48, 5, 128, 128], [48, 24, 10, 256, 256]]
        scale_factor: 2
      omit_skip_connections: False
  unet_ob:
    freeze: False
    checkpoint: False
    decoder:
      output_dim: 4
      f_maps: [96, 192, 384, 768]
      basic_module: 'DoubleConv'
      conv_kernel_size: 3
      conv_padding: 1
      layer_order: 'gcr'
      num_groups: 8
      is3d: True
      layers_no_skip:
        size: [[96, 48, 5, 128, 128], [48, 24, 10, 256, 256]]
        scale_factor: 2 
      omit_skip_connections: False