data:
  dir: 'data/SIAR'

wandb:
  logger: False

train:
  debug: True
  batch_size: 16
  max_epochs: 100
  log_every_n_steps: 10

model:
  upsampler: 'unet'
  swin:
    pretrained: ''
    use_checkpoint: True
    patch_size: [2, 4, 4]    
  unet:
    decoder:
      output_dim: 3
      f_maps: [96, 192, 384, 768]
      basic_module: 'DoubleConv'
      conv_kernel_size: 3
      conv_padding: 1
      layer_order: 'gcr'
      num_groups: 8
      is3d: True
      layers_no_skip:
        size: [[96, 48, 5, 128, 128], [48, 24, 10, 256, 256]]
        scale_factor: 2 

