data:
  dir: '/netscratch/herzig/datasets/SIAR'
  
train:
  debug: False
  batch_size: 8
  max_epochs: 30
  log_every_n_steps: 15
  device: 'gpu'

model:
  checkpoint: False
  upsampler_gt: 'unet' # upsampler for ground truth
  upsampler_sl: 'unet' # upsampler for shadow and light
  upsampler_ob: 'unet' # upsampler for objects (masks + rgb)
  swin:
    pretrained: ''
    use_checkpoint: False
    patch_size: [2, 4, 4]    
  unet_gt:
    decoder:
      output_dim: 3
      f_maps: [96, 192, 384, 768]
      basic_module: 'DoubleConv'
      conv_kernel_size: 3
      conv_padding: 1
      layer_order: 'gcr'
      num_groups: 8
      is3d: True
      layers_no_skip:
        size: [[96, 48, 5, 128, 128], [48, 24, 1, 256, 256]]
        scale_factor: 2 
  unet_sl:
    decoder:
      output_dim: 2
      f_maps: [96, 192, 384, 768]
      basic_module: 'DoubleConv'
      conv_kernel_size: 3
      conv_padding: 1
      layer_order: 'gcr'
      num_groups: 8
      is3d: True
      layers_no_skip:
        size: [[96, 48, 5, 128, 128], [48, 24, 10, 256, 256]]
        scale_factor: 2
  unet_ob:
    decoder:
      output_dim: 4
      f_maps: [96, 192, 384, 768]
      basic_module: 'DoubleConv'
      conv_kernel_size: 3
      conv_padding: 1
      layer_order: 'gcr'
      num_groups: 8
      is3d: True
      layers_no_skip:
        size: [[96, 48, 5, 128, 128], [48, 24, 10, 256, 256]]
        scale_factor: 2 
