data:
  dir: 'data/SIAR'

wandb:
  logger: True

train:
  debug: False
  batch_size: 16
  max_epochs: 20
  log_every_n_steps: 10
  device: 'gpu'

model:
  checkpoint: False
  upsampler_gt: 'swin' # upsampler for ground truth
  upsampler_sl: 'swin' # upsampler for shadow and light
  upsampler_ob: 'swin' # upsampler for objects (masks + rgb)
  upsampler: 'swin'
  swin:
    pretrained: ''
    use_checkpoint: False
    patch_size: [2, 4, 4]  
  

