data:
  dir: 'data/SIAR'

wandb:
  logger: False

train:
  debug: True
  batch_size: 32
  max_epochs: 100
  log_every_n_steps: 15
  device: 'gpu'

model:
  upsampler: 'swin'
  swin:
    pretrained: ''
    use_checkpoint: True
    patch_size: [2, 4, 4]    
  

